CustomAuth/ViewModels/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using DalToWeb.ORM;

namespace CustomAuth.ViewModels
{
    public class ArticleViewModel
    {
        public int Id { get; set; }
        public int BlogId { get; set; }
        public int Views { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public DateTime TimeAdded { get; set; }
        public string Content { get; set; }
        public string ImagePath { get; set; }
        public ICollection<Tag> Tags { get; set; } 
        public List<CommentModel> Comments { get; set; } 
    }
}

CustomAuth/Controllers/ArticleController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Bll.Interface.Entities;
using Bll.Interface.Services;
using CustomAuth.Infrastructure.Mappers;
using CustomAuth.Utils;
using CustomAuth.ViewModels;
using DalToWeb.ORM;

namespace CustomAuth.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly IUserService _userService;
        private readonly IBlogService _blogService;
        private readonly IArticleService _articleService;
        private readonly ICommentService _commentService;

        public ArticleController(IUserService service, IBlogService blogService,
            IArticleService articleService, ICommentService commentService)
        {
            _userService = service;
            _blogService = blogService;
            _articleService = articleService;
            _commentService = commentService;
        }

        [AllowAnonymous]
        public ActionResult Index(int page = 1)
        {
            var articles = _articleService
                .TakeLastArticleEntities(page, 10)
                .Select(a => a.ToMvcViewArticleCommon())
                .ToList(); ;

            if (page == 1)
                return View(articles);
            
            var itsAll = (articles.Count == 10) ? "no" : "yes";
            
            var dataForJson = new ArrayList {itsAll};
            dataForJson.AddRange(articles);
            return Json(dataForJson, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CreateArticle()
        {
            var currentUser = _userService.GetUserEntity(User.Identity.Name);
            int userId = currentUser.Id;
            var myBlogs = _blogService
                .GetAllBlogEntities()
                .Where(b => b.UserId == userId)
                .ToList();

            List<SelectListItem> list = new List<SelectListItem>();
            list.AddRange(myBlogs.Select(b => new SelectListItem() { Value = b.Id.ToString(), Text = b.Name }));

            ViewBag.list = list;
            return View();
        }

        [HttpPost]
        public ActionResult CreateArticle(ArticleViewModelCreate article, HttpPostedFileBase img)
        {
            if (ModelState.IsValid)
            {
                var str = new StringBuilder();
                if (img != null)
                    str.Append(FileHelper.SaveFileToDisk(img, Server.MapPath("~/")));

                _articleService.CreateArticle(article.ToBllArticle(str.ToString()));
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Details(string id)
        {
            try
            {
                var art = GetArticle(id);
                _articleService.IncrementViews(art.Id);
                art.Comments = new List<CommentModel>();
                art.Views++;
                var comments = _commentService.GetAllCommentEntities(art.Id).ToList();
                foreach (var comment in comments)
                {
                    var user = _userService.GetUserEntity(comment.UserId);
                    var c = new CommentModel()
                    {
                        Id = comment.Id,
                        ArticleId = comment.ArticleId,
                        TextComment = comment.CommentText,
                        Date = comment.DateAdded.ToString(),
                        Author = user.UserName,
                        AvatarPath = user.AvatarPath
                    };
                    art.Comments.Add(c);
                }
                return View(art);
            }
            catch (ArgumentOutOfRangeException)
            {
                return RedirectToAction("Error", "Home");
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [Authorize(Roles = "Moderator,Admin")]
        [HttpGet]
        public ActionResult Edit(string id)
        {
            try
            {
                var art = GetArticle(id);
                TempData["Tags"] = art.Tags;
                return View(art);
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error", "Home");
            }
            catch (ArgumentOutOfRangeException)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [Authorize(Roles = "Moderator,Admin")]
        [HttpPost]
        public ActionResult Edit(ArticleViewModel model)
        {
            model.Tags = (ICollection<Tag>)TempData["Tags"];
            _articleService.UpdateArticle(model.ToArticleEntity());
            return RedirectToAction("Blogs", "Blog");
        }

        [Authorize(Roles = "Moderator,Admin")]
        public ActionResult Delete(int id)
        {
            var filePath = _articleService.GetArticleEntity(id).ImagePath;
            _articleService.DeleteArticle(id);
            if (filePath != null)
                FileHelper.RemoveFileFromDisk(Server.MapPath("~/"), filePath);

            if (Request.IsAjaxRequest())
                return Content("ok");

            return RedirectToAction("Details", "Blog", new { id = TempData["BlogId"].ToString() });
        }
        #region Private methods
        private ArticleViewModel GetArticle(string id)
        {
            int parsedId;
            if (int.TryParse(id, out parsedId) == false)
                throw new NullReferenceException();

            if (parsedId < 0)
                throw new ArgumentOutOfRangeException();

            TempData["CurrentArticle"] = parsedId;
            return _articleService.GetArticleEntity(parsedId).ToMvcViewArticle();  
        }
        #endregion
    }
}

CustomAuth/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bll.Interface.Entities;
using Bll.Interface.Services;
using CustomAuth.Infrastructure.Mappers;
using CustomAuth.Utils;
using CustomAuth.ViewModels;

namespace CustomAuth.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        private readonly IUserService _userService;
        private readonly ICommentService _commentService;

        public CommentController(IUserService service, ICommentService commentService)
        {
            _userService = service;
            _commentService = commentService;
        }
        [HttpPost]
        public ActionResult NewComment(string textComment)
        {
            int id = (int) TempData["CurrentArticle"];
            if (!string.IsNullOrEmpty(textComment))
            {
                var user = _userService.GetUserEntity(User.Identity.Name);
                var comment = new CommentModel
                {
                    Id = _commentService.GetLastId(),
                    Author = User.Identity.Name,
                    Date = DateTime.Now.ToString(),
                    TextComment = textComment,
                    ArticleId = id,
                    AvatarPath = user.AvatarPath
                };

                _commentService.CreateComment(comment.ToCommentEntity(user.Id));

                if (Request.IsAjaxRequest())
                {
                    TempData["CurrentArticle"] = id;
                    return Json(comment);
                }
            }
            return RedirectToAction("Details", "Article", new {id = id});
        }

        [Authorize(Roles = "Moderator,Admin")]
        [HttpGet]
        public ActionResult EditComment(string data)
        {
            var array = data.Split('~');
            int id = int.Parse(array[0]);
            string text = array[1];
            _commentService.UpdateComment(new CommentEntity {Id = id,CommentText = text});
            return Content("ok");
        }

        [Authorize(Roles = "Moderator,Admin")]
        [HttpGet]
        public ActionResult DeleteComment(int id)
        {
            _commentService.DeleteComment(id);
            return Content("ok");
        }
    }
}

CustomAuth/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bll.Interface.Services;
using CustomAuth.Infrastructure.Mappers;
using CustomAuth.Pagination;
using CustomAuth.Utils;
using CustomAuth.ViewModels;
using DalToWeb.Interfacies;
using WebGrease.Css.Extensions;
using ListExtensions = WebGrease.Css.Extensions.ListExtensions;

namespace CustomAuth.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        private readonly IUserService _userService;
        private readonly IBlogService _blogService;
        private readonly IArticleService _articleService;
        private readonly ITagRepository _tagRepository;

        public SearchController(IArticleService articleService, ITagRepository tagRepository,
            IBlogService blogService, IUserService userService)
        {
            _articleService = articleService;
            _tagRepository = tagRepository;
            _blogService = blogService;
            _userService = userService;
        }
        public ActionResult ByTag(string tag)
        {
            var tags = _tagRepository.GetAll().Where(t => t.TagField == tag).ToList();
            var listId = (from t in tags from art in t.Articles select art.Id).ToList();

            var articles = _articleService.GetAllArticleEntities().ToList();
            var model = new List<ArticleViewModelCommon>();
            foreach (var art in articles)
                foreach (var id in listId)
                    if (art.Id == id)
                    {
                        var blog = _blogService.GetBlogEntity(art.BlogId);
                        var authorName = _userService.GetUserEntity(blog.UserId).UserName;
                        model.Add(art.ToMvcViewArticleCommon());
                    }
            return View(model);
        }

        public ActionResult ByText(string substring)
        {
            var arts = _articleService.FindArticlesBySubstring(substring).ToList();
            var model = new List<ArticleViewModelCommon>();
            foreach (var art in arts)
            {
                var blog = _blogService.GetBlogEntity(art.BlogId);
                var authorName = _userService.GetUserEntity(blog.UserId).UserName;
                model.Add(art.ToMvcViewArticleCommon());
            }
            return View(model);
        }

        public ActionResult Blogs(string blogTitle,int page = 1, int codeSort = 0)
        {
            var blogs = _blogService
                .GetAllBlogEntities()
                .Where(b => b.Name == blogTitle)
                .ToList();

            var models = blogs
                .Skip((page - 1) * 10)
                .Take(10)
                .Select(bl => bl.ToMvcBlog())
                .ToList();
            #region заполнить имена авторов
            foreach (var m in models)
            {
                var uId = _blogService.GetBlogEntity(m.Id).UserId;
                m.ArticleCount = _articleService.GetAllArticleEntities(m.Id).Count();
                m.UserName = _userService.GetUserEntity(uId).UserName;
            }
            #endregion

            string infoForGlyphicons;
            var comparer = BlogSorts.GetMethod(codeSort, out infoForGlyphicons);
            if (comparer != null)
                models.Sort(comparer);

            ViewBag.Direction = infoForGlyphicons;

            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = 10, TotalItems = blogs.Count() };
            var bvm = new BlogsViewModel { PageInfo = pageInfo, BlogViewModels = models };
            ViewBag.blogTitle = blogTitle;
            
            return View(bvm);
        }
    }
}

CustomAuth/Views/Article/CreateArticle.cshtml
@model CustomAuth.ViewModels.ArticleViewModelCreate


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/ForWebUI/CreateArticle.js"></script>

<div class="col-lg-6">
    @using (Html.BeginForm("CreateArticle", "Article", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4 style="text-align: center">Create new article</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2">Title</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group ">
                <label class="control-label col-md-2" for="Blog">Blog</label>
                <div class="col-md-10">
                    <select class="form-control" name="Blog">
                        <option value="" selected="selected" content="empty" class="text-muted">Select blog</option>
                        @foreach (var c in ViewBag.list)
                        {
                            <option value="@c.Value">@c.Text</option>
                        }
                    </select>
                </div>
                <span class="field-validation-error text-danger" data-valmsg-for="Blog" data-valmsg-replace="true"></span>
            </div>
            <br />
            <div class="form-group">
                <label class="control-label col-md-2" for="Content">Content</label>
                <div class="col-lg-10">
                    <textarea class="form-control" rows="3" name="Content" id="Content"></textarea>
                    <span class="field-validation-error text-danger" data-valmsg-for="Content" data-valmsg-replace="true"></span>
                </div>
            </div>
            <div class="form-group">
                <label for="tags" class="col-lg-2 control-label">Tags</label>
                <div class="col-lg-10">
                    <input type="text" class="form-control" id="tags" name="tags" placeholder="tag1,tag2,..">
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-picture"></i></span>
                    <input type="text" class="form-control" placeholder="Attach image" id="inputFileVisibleText">
                    <input type="file" style="display: none" name="img" id="inputFileHidden" />
                    <span class="input-group-btn" style="float: left">
                        <button class="btn btn-default" type="button" id="inputFileVisibleBtn">Browse</button>
                    </span>
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Home", "Index", "Article")
    </div>
</div>

CustomAuth/Views/Article/Details.cshtml
@using System.Diagnostics.Eventing.Reader
@model CustomAuth.ViewModels.ArticleViewModel

@{
    ViewBag.Title = "Article details";
}

@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/ForWebUI/ArticleDetails.js"></script>

<script>
    $(document).ready(function () {
        $("#commentArticle").click(function () {
            var method = $("form#formComment").attr('method');
            var action = $("form#formComment").attr('action');
            var data = { 'textComment': $("#textComment").val() };

            $.ajax({
                type: method,
                url: action,
                data: JSON.stringify(data),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (comment) {
                    $("#textComment").val('');
                    $("#commentContainer").append("<div class='panel panel-default' onmouseover='ShowGlyphs(this)' onmouseout='HideGlyphs(this)' id=" + comment.Id + ">" +
                                                        "<div class='panel-body'>" +
                                                            "<img style='width: 50px; height: 50px;' src='/UserContent/" + comment.AvatarPath + "' alt='No avatar'/>" +
                                                            "<span style='font-size: 12px;'>" + "  " + comment.Author + " </span><span style='font-size: 12px;'>" + comment.Date + " </span>" +
                                                                "<div class='glyphicon glyphicon-trash hidden' style='float: right;' id='trash_" + comment.Id + "' onclick='DeleteElement(this)'></div>" +
                                                                "<div class='glyphicon glyphicon-edit hidden' style='float: right;' id='edit_" + comment.Id + "' onclick='EditComment(this)'></div>" +
                                                                "<div id='commentEditInput_" + comment.Id + "' class='editing' style='height: auto; width: 300px; text-align: center;'></div>" +
                                                                "<br/>" +
                                                                "<p style='font-size: 16px;' id='comment_" + comment.Id + "'>" + comment.TextComment + "</p>" +
                                                        "</div>" +
                                                    "</div>");
                }
            });
            return false;
        }
        );
    });
</script>

<div class="col-md-9">
    <div class="panel panel-default">
        <div class="panel-body">
            <h2>@Model.Title</h2>
            <b>
                <span> | Published by @Model.Author</span>
                <span> | @Model.TimeAdded |</span>
                <br />
                | <i>
                    Tags:
                    @if (Model.Tags != null)
                    {
                        foreach (var tag in Model.Tags)
                        {
                            <a href="@Url.Action("ByTag", "Search", new {tag = tag.TagField})" class="btn btn-primary btn-xs">@tag.TagField</a>
                        }
                    }
                    else
                    {
                        <span>none</span>
                    }
                </i>
                <br/>
                <span> | Viewed: @Model.Views |</span>
            </b>
            <br />
            <img src="/UserContent/@Model.ImagePath" width="33%" height="30%" alt="post img" style="float: left; margin: 7px 7px 7px 7px;">
            <span style="word-wrap: break-word">@Model.Content</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6" id="commentContainer">
            @if (Model.Comments != null)
            {
                <h4>Comments:</h4>
                foreach (var comment in Model.Comments)
                {
                    <div class="panel panel-default" onmouseover="ShowGlyphs(this)" onmouseout="HideGlyphs(this)" id="@comment.Id">
                        <div class="panel-body">
                            <img style="width: 50px; height: 50px;" src="/UserContent/@comment.AvatarPath" alt="No avatar"/>
                            <span style="font-size: 12px;">@comment.Author </span>
                            <span style="font-size: 12px;"> @comment.Date</span>
                            <div class="glyphicon glyphicon-trash hidden" style="float: right;" id="trash_@comment.Id" onclick="DeleteElement(this)"></div>
                            <div class="glyphicon glyphicon-edit hidden" style="float: right;" id="edit_@comment.Id" onclick="EditComment(this)"></div>
                            <div id="commentEditInput_@comment.Id" class="editing" style="height: auto; width: 300px; text-align: center;"></div>
                            <br/>
                            <p style="font-size: 16px;" id="comment_@comment.Id">@comment.TextComment</p>
                        </div>
                    </div>
                }
            }  
        </div>
    </div>
    <br/>
    <hr/>
    @using (Html.BeginForm("NewComment", "Comment", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", @id = "formComment", @style = "margin-left: 15px;" }))
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label class="control-label">Leave a comment</label>
            <input type="text" class="form-control" name="textComment" id="textComment">
        </div>
        <input type="submit" class="btn btn-default" id="commentArticle" value="Comment" />
    }
</div>

CustomAuth/Views/Article/Edit.cshtml
@model CustomAuth.ViewModels.ArticleViewModel

@{
    ViewBag.Title = "Change article";
}

<div class="col-lg-6">
    @using (Html.BeginForm("Edit", "Article", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("Id", Model.Id)
        @Html.Hidden("BlogId", Model.BlogId)
        @Html.Hidden("Title", Model.Title)
        @Html.Hidden("Author", Model.Author)
        @Html.Hidden("ImagePath", Model.ImagePath)
        @Html.Hidden("TimeAdded", Model.TimeAdded)
        <div class="form-horizontal">
            <h4 style="text-align: center">Change this article @Model.Title</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-lg-2" for="Content">Content</label>
                <div class="col-lg-10">
                    <textarea class="form-control" rows="9" name="Content" id="Content">@Model.Content</textarea>
                    <span class="field-validation-error text-danger" data-valmsg-for="Content" data-valmsg-replace="true"></span>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </div>
    }
</div>

CustomAuth/Views/Article/Index.cshtml
@model List<CustomAuth.ViewModels.ArticleViewModelCommon>

@{
    ViewBag.Title = "Home page";
}
@Scripts.Render("~/bundles/jquery")

<script>
    $(document).ready(function () {
        $("#getMorePanel").hover(function () { $(this).css("background", "gainsboro"); }, function () { $(this).css("background", "white") });
    });
</script>

<script>
    var p = 1;
    function getMore() {
        p = p + 1;
        $.get("/Article/Index?page=" + p, function (data) {
            alert(data);
            if (data[0] === "yes") {
                $("#getMorePanel").remove();
            }
            var newAtrs = '';
            for (var i = 1; i < data.length; i++) {
                var art = data[i];
                newAtrs += "<div class='well'>" +
                                "<div class='media'>" +
                                    "<a class='pull-left' href='#'>" +
                                        "<img class='media-object' src='/UserContent/" + art.ImagePath + "' width='150px' height='150px'>" +
                                    "</a>" +
                                    "<div class='media-body'>" +
                                        "<h4 class='media-heading'>"+ art.Title+"</h4>" +
                                        "<p>" + art.Author + "</p>" +
                                        "<p>" + art.Content + "</p>" +
                                        "<ul class='list-inline list-unstyled'>" +
                                            "<li><span><i class='glyphicon glyphicon-calendar'></i>  " +art.Date+ " </span></li>" +
                                            "<li>|</li><span><i class='glyphicon glyphicon-eye-open'></i> " + art.Viewed + " </span>" +
                                            "<li>|</li><span><i class='glyphicon glyphicon-comment'></i> "+art.CommentCount+" </span>" +
                                            "<li>|</li></ul>" +
                                            "<div><a href='/Article/Details/"+art.Id+"' class='btn btn-primary btn-xs'>Read more</a></div>" +
                                    "</div>" +
                                "</div>" +
                            "</div>";
            }
            $("#ArtContainer").append(newAtrs);
        });
    }
</script>

<div class="col-lg-9">
    @if (User.Identity.IsAuthenticated)
    {
        <h2 style="text-align: center">Recently added articles</h2>
        <hr/>
        <div id="ArtContainer">
            @foreach (var article in Model)
            {
                <div class="well">
                    <div class="media">
                        <a class="pull-left" href="#">
                            <img class="media-object" src="~/UserContent/@article.ImagePath" width="150px" height="150px">
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading">@article.Title</h4>
                            <p>@article.Author</p>
                            <p>
                                @article.Content
                            </p>
                            <ul class="list-inline list-unstyled">
                                <li><span><i class="glyphicon glyphicon-calendar"></i> @article.Date </span></li>
                                <li>|</li>
                                <span><i class="glyphicon glyphicon-eye-open"></i> @article.Viewed </span>
                                <li>|</li>
                                <span><i class="glyphicon glyphicon-comment"></i> @article.CommentCount </span>
                                <li>|</li>
                            </ul>
                            <div>
                                <a href="@Url.Action("Details", "Article", new {Id = article.Id})" class="btn btn-primary btn-xs">Read more</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="panel panel-default" id="getMorePanel">
            <div href="" class="panel-body" id="getMoreArts" onclick="getMore()">
                <p style="text-align: center">See more</p>
            </div>
        </div>
    }
    else
    {
        <div class="jumbotron">
            <h1>Welcome</h1>
            <p class="lead">Share news and learn about new events in the world</p>
            <p><a class="btn btn-lg btn-default" href="@Url.Action("Register","Account")" role="button">Sign up today</a>
            </p>
        </div>
        <div class="row marketing">
            <div class="col-lg-6">
                <h4>Articles</h4>
                <p>Place your articles for certain categories</p>

                <h4>Photos</h4>
                <p>Attach photo to articles</p>
            </div>

            <div class="col-lg-6">
                <h4>Comment</h4>
                <p>Discuss your articles and articles of other users</p>

                <h4>Search</h4>
                <p>Look for interesting article</p>
            </div>
        </div>
    }
</div>