CustomAuth/ViewModels/BlogsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using CustomAuth.Pagination;

namespace CustomAuth.ViewModels
{
    public class BlogsViewModel
    {
        public int UserId { get; set; }
        public IEnumerable<BlogViewModel> BlogViewModels { get; set; }
        public PageInfo PageInfo { get; set; }
    }

    public class BlogViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Blog title")]
        public string Title { get; set; }

        [Display(Name = "Date created")]
        public DateTime CreationDate { get; set; }

        public int ArticleCount { get; set; }
        public string UserName { get; set; }
    }
}

CustomAuth/Controllers/ArticleController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Bll.Interface.Entities;
using Bll.Interface.Services;
using CustomAuth.Infrastructure.Mappers;
using CustomAuth.Utils;
using CustomAuth.ViewModels;
using DalToWeb.ORM;

namespace CustomAuth.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly IUserService _userService;
        private readonly IBlogService _blogService;
        private readonly IArticleService _articleService;
        private readonly ICommentService _commentService;

        public ArticleController(IUserService service, IBlogService blogService,
            IArticleService articleService, ICommentService commentService)
        {
            _userService = service;
            _blogService = blogService;
            _articleService = articleService;
            _commentService = commentService;
        }

        [AllowAnonymous]
        public ActionResult Index(int page = 1)
        {
            var articles = _articleService
                .TakeLastArticleEntities(page, 10)
                .Select(a => a.ToMvcViewArticleCommon())
                .ToList(); ;

            if (page == 1)
                return View(articles);
            
            var itsAll = (articles.Count == 10) ? "no" : "yes";
            
            var dataForJson = new ArrayList {itsAll};
            dataForJson.AddRange(articles);
            return Json(dataForJson, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CreateArticle()
        {
            var currentUser = _userService.GetUserEntity(User.Identity.Name);
            int userId = currentUser.Id;
            var myBlogs = _blogService
                .GetAllBlogEntities()
                .Where(b => b.UserId == userId)
                .ToList();

            List<SelectListItem> list = new List<SelectListItem>();
            list.AddRange(myBlogs.Select(b => new SelectListItem() { Value = b.Id.ToString(), Text = b.Name }));

            ViewBag.list = list;
            return View();
        }

        [HttpPost]
        public ActionResult CreateArticle(ArticleViewModelCreate article, HttpPostedFileBase img)
        {
            if (ModelState.IsValid)
            {
                var str = new StringBuilder();
                if (img != null)
                    str.Append(FileHelper.SaveFileToDisk(img, Server.MapPath("~/")));

                _articleService.CreateArticle(article.ToBllArticle(str.ToString()));
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Details(string id)
        {
            try
            {
                var art = GetArticle(id);
                _articleService.IncrementViews(art.Id);
                art.Comments = new List<CommentModel>();
                art.Views++;
                var comments = _commentService.GetAllCommentEntities(art.Id).ToList();
                foreach (var comment in comments)
                {
                    var user = _userService.GetUserEntity(comment.UserId);
                    var c = new CommentModel()
                    {
                        Id = comment.Id,
                        ArticleId = comment.ArticleId,
                        TextComment = comment.CommentText,
                        Date = comment.DateAdded.ToString(),
                        Author = user.UserName,
                        AvatarPath = user.AvatarPath
                    };
                    art.Comments.Add(c);
                }
                return View(art);
            }
            catch (ArgumentOutOfRangeException)
            {
                return RedirectToAction("Error", "Home");
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [Authorize(Roles = "Moderator,Admin")]
        [HttpGet]
        public ActionResult Edit(string id)
        {
            try
            {
                var art = GetArticle(id);
                TempData["Tags"] = art.Tags;
                return View(art);
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error", "Home");
            }
            catch (ArgumentOutOfRangeException)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        [Authorize(Roles = "Moderator,Admin")]
        [HttpPost]
        public ActionResult Edit(ArticleViewModel model)
        {
            model.Tags = (ICollection<Tag>)TempData["Tags"];
            _articleService.UpdateArticle(model.ToArticleEntity());
            return RedirectToAction("Blogs", "Blog");
        }

        [Authorize(Roles = "Moderator,Admin")]
        public ActionResult Delete(int id)
        {
            var filePath = _articleService.GetArticleEntity(id).ImagePath;
            _articleService.DeleteArticle(id);
            if (filePath != null)
                FileHelper.RemoveFileFromDisk(Server.MapPath("~/"), filePath);

            if (Request.IsAjaxRequest())
                return Content("ok");

            return RedirectToAction("Details", "Blog", new { id = TempData["BlogId"].ToString() });
        }
        #region Private methods
        private ArticleViewModel GetArticle(string id)
        {
            int parsedId;
            if (int.TryParse(id, out parsedId) == false)
                throw new NullReferenceException();

            if (parsedId < 0)
                throw new ArgumentOutOfRangeException();

            TempData["CurrentArticle"] = parsedId;
            return _articleService.GetArticleEntity(parsedId).ToMvcViewArticle();  
        }
        #endregion
    }
}

CustomAuth/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bll.Interface.Entities;
using Bll.Interface.Services;
using BLL;
using CustomAuth.Infrastructure.Mappers;
using CustomAuth.Pagination;
using CustomAuth.ViewModels;
using DalToWeb;
using WebGrease.Css.Extensions;

namespace CustomAuth.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly IUserService _userService;
        private readonly IArticleService _articleService;

        public BlogController(IBlogService blogService, IUserService userservice, IArticleService articleService)
        {
            this._blogService = blogService;
            _userService = userservice;
            _articleService = articleService;
        }

        [HttpGet]
        public ActionResult CreateBlog() => View();


        [HttpPost]
        public ActionResult CreateBlog(UserBlogModel blog)
        {
            var currentUser = _userService.GetUserEntity(User.Identity.Name);
            int userId = currentUser.Id;
            var anyBlogs = _blogService
                .GetAllBlogEntities()
                .Where(b => b.Name == blog.Title);

            if (anyBlogs.FirstOrDefault(b => b.UserId == userId) != null)
            {
                ModelState.AddModelError("", "У вас уже есть блог с таким названием");
                return View(blog);
            }

            if (ModelState.IsValid)
            {
                _blogService.CreateBlog(blog.ToBllBlog(userId));
                return RedirectToAction("Blogs", "Blog");
            }
            return View();
        }

        public ActionResult Blogs(int uId = 0, int page = 1)
        {
            var currentUser = _userService.GetUserEntity(User.Identity.Name);
            int userId = (uId == 0) ? currentUser.Id : uId;
            var blogs = _blogService
                .GetAllBlogEntities()
                .Where(b => b.UserId == userId)
                .ToList();

            var models = blogs
                .Skip((page - 1) * 10)
                .Take(10)
                .Select(bl => bl.ToMvcBlog())
                .ToList();

            foreach (var m in models)
            {
                m.ArticleCount = _articleService
                    .GetAllArticleEntities(m.Id)
                    .Count();
            }
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = 10, TotalItems = blogs.Count() };
            var bvm = new BlogsViewModel { PageInfo = pageInfo, BlogViewModels = models };
            bvm.UserId = userId;

            return View(bvm);
        }

        public ActionResult Details(string id, int page = 1)
        {
            try
            {
                var blog = GetBlog(id);
                TempData["BlogId"] = blog.Id;
                ViewBag.IsModerating =
                    (blog.UserId == _userService.GetUserEntity(User.Identity.Name).Id)
                    || User.IsInRole("Moderator") || User.IsInRole("Admin");

                ViewBag.Id = id;
                ViewBag.DateCreated = blog.DateAdded;
                ViewBag.BlogName = blog.Name;

                var articles = _articleService
                    .GetAllArticleEntities(blog.Id)
                    .ToList();

                var models = articles
                    .Skip((page - 1) * 15)
                    .Take(15)
                    .Select(a => a.ToMvcArticle())
                    .ToList();

                var pageInfo = new PageInfo { PageNumber = page, PageSize = 15, TotalItems = articles.Count() };
                var model = new ArticleViewModelPagination { ArticleViewModels = models, PageInfo = pageInfo };

                return View(model);
            }
            catch (NullReferenceException)
            {
                return RedirectToAction("Error", "Home");
            }
            catch (ArgumentOutOfRangeException)
            {
                return RedirectToAction("Error", "Home");
            }       
        }

        private BlogEntity GetBlog(string id)
        {
            int parsedId;
            if (int.TryParse(id, out parsedId) == false)
                throw new NullReferenceException();

            if (parsedId < 0)
                throw new ArgumentOutOfRangeException();

            return _blogService.GetBlogEntity(parsedId);
        }
    }
}

CustomAuth/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bll.Interface.Services;
using CustomAuth.Infrastructure.Mappers;
using CustomAuth.Pagination;
using CustomAuth.Utils;
using CustomAuth.ViewModels;
using DalToWeb.Interfacies;
using WebGrease.Css.Extensions;
using ListExtensions = WebGrease.Css.Extensions.ListExtensions;

namespace CustomAuth.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        private readonly IUserService _userService;
        private readonly IBlogService _blogService;
        private readonly IArticleService _articleService;
        private readonly ITagRepository _tagRepository;

        public SearchController(IArticleService articleService, ITagRepository tagRepository,
            IBlogService blogService, IUserService userService)
        {
            _articleService = articleService;
            _tagRepository = tagRepository;
            _blogService = blogService;
            _userService = userService;
        }
        public ActionResult ByTag(string tag)
        {
            var tags = _tagRepository.GetAll().Where(t => t.TagField == tag).ToList();
            var listId = (from t in tags from art in t.Articles select art.Id).ToList();

            var articles = _articleService.GetAllArticleEntities().ToList();
            var model = new List<ArticleViewModelCommon>();
            foreach (var art in articles)
                foreach (var id in listId)
                    if (art.Id == id)
                    {
                        var blog = _blogService.GetBlogEntity(art.BlogId);
                        var authorName = _userService.GetUserEntity(blog.UserId).UserName;
                        model.Add(art.ToMvcViewArticleCommon());
                    }
            return View(model);
        }

        public ActionResult ByText(string substring)
        {
            var arts = _articleService.FindArticlesBySubstring(substring).ToList();
            var model = new List<ArticleViewModelCommon>();
            foreach (var art in arts)
            {
                var blog = _blogService.GetBlogEntity(art.BlogId);
                var authorName = _userService.GetUserEntity(blog.UserId).UserName;
                model.Add(art.ToMvcViewArticleCommon());
            }
            return View(model);
        }

        public ActionResult Blogs(string blogTitle,int page = 1, int codeSort = 0)
        {
            var blogs = _blogService
                .GetAllBlogEntities()
                .Where(b => b.Name == blogTitle)
                .ToList();

            var models = blogs
                .Skip((page - 1) * 10)
                .Take(10)
                .Select(bl => bl.ToMvcBlog())
                .ToList();
            #region заполнить имена авторов
            foreach (var m in models)
            {
                var uId = _blogService.GetBlogEntity(m.Id).UserId;
                m.ArticleCount = _articleService.GetAllArticleEntities(m.Id).Count();
                m.UserName = _userService.GetUserEntity(uId).UserName;
            }
            #endregion

            string infoForGlyphicons;
            var comparer = BlogSorts.GetMethod(codeSort, out infoForGlyphicons);
            if (comparer != null)
                models.Sort(comparer);

            ViewBag.Direction = infoForGlyphicons;

            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = 10, TotalItems = blogs.Count() };
            var bvm = new BlogsViewModel { PageInfo = pageInfo, BlogViewModels = models };
            ViewBag.blogTitle = blogTitle;
            
            return View(bvm);
        }
    }
}

CustomAuth/Views/Search/Blogs.cshtml
@using CustomAuth.Pagination
@using CustomAuth.Utils
@model CustomAuth.ViewModels.BlogsViewModel

@{
    ViewBag.Title = "Search blogs";
}

<div class="col-lg-9">
    @if (Model.BlogViewModels.Count() != 0)
    {
        <h2>Search results</h2>
        <br />
        <table class="table table-hover" style="color: blue">
            <tr>
                @for (int i = 0; i < 5; i++)
                {
                    <th class="hidden"></th>
                }
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                @if (ViewBag.Direction == "postsDown")
                {
                    <td><a href="@Url.Action("Blogs", new { blogTitle = ViewBag.blogTitle, codeSort = 1})" class="btn btn-primary btn-xs">articles<span><i class="glyphicon glyphicon-arrow-down"></i></span></a></td>
                }
                else
                {
                    <td><a href="@Url.Action("Blogs", new { blogTitle = ViewBag.blogTitle, codeSort = 0})" class="btn btn-primary btn-xs">articles<span><i class="glyphicon glyphicon-arrow-up"></i></span></a></td>
                }
                <td></td>
            </tr>
            @foreach (var item in Model.BlogViewModels)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        <span><i class="glyphicon glyphicon-user"></i> @Html.DisplayFor(modelItem => item.UserName) </span>
                    </td>
                    <td>
                        <span><i class="glyphicon glyphicon-calendar"></i> @Html.DisplayFor(modelItem => item.CreationDate) </span>
                    </td>
                    <td>
                        <span><i class="glyphicon glyphicon-pencil"></i> @Html.DisplayFor(modelItem => item.ArticleCount) </span>
                    </td>
                    <td>
                        <a href="@Url.Action("Details","Blog", new {id = item.Id})" class="btn btn-xs btn-default">read more</a>
                    </td>
                </tr>
            }
        </table>
        if (Model.PageInfo.TotalPages != 1)
        {
            <div class="btn-group">
                @Html.PageLinks(Model.PageInfo, x => Url.Action("Blogs", new { blogTitle = ViewBag.blogTitle, page = x }))
            </div>
        }
    }
    else
    {
        <h2 style="text-align: center">Ничего не найдено</h2>
    }
</div>

CustomAuth/Views/Search/ByTag.cshtml
@model List<CustomAuth.ViewModels.ArticleViewModelCommon>

@{
    ViewBag.Title = "Search";
}

<div class="col-lg-9">
    @if (Model.Count != 0)
    {
        <h4 style="text-align: center">Search results</h4>
        <hr/>
        foreach (var article in Model)
        {
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>@article.Title</h2>
                    <img src="~/UserContent/@article.ImagePath" width="150px" height="150px" alt="post img" class="pull-left img-responsive thumb margin10 img-thumbnail">

                    <em>@article.Author</em>
                    <article>
                        <p>
                            @article.Content
                        </p>
                    </article>
                    <a class="btn btn-xs btn-primary pull-right marginBottom10" href="@Url.Action("Details", "Article", new {Id = article.Id})">read more</a>
                </div>
            </div>
            <br/>
        }
    }
    else
    {
        <h2 style="text-align: center">Nothing found</h2>
    }
</div>

CustomAuth/Views/Search/ByText.cshtml
@model List<CustomAuth.ViewModels.ArticleViewModelCommon>

@{
    ViewBag.Title = "Search results";
}

<div class="col-lg-9">
    @if (Model.Count != 0)
    {
        <h4 style="text-align: center">Search results</h4>
        <hr />
        foreach (var article in Model)
        {
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>@article.Title</h2>
                    <img src="~/UserContent/@article.ImagePath" width="150px" height="150px" alt="post img" class="pull-left img-responsive thumb margin10 img-thumbnail">

                    <em>@article.Author</em>
                    <article>
                        <p>
                            @article.Content
                        </p>
                    </article>
                    <a class="btn btn-xs btn-primary pull-right marginBottom10" href="@Url.Action("Details", "Article", new {Id = article.Id})">read more</a>
                </div>
            </div>
            <br />
        }
    }
    else
    {
        <h2 style="text-align: center">Nothing found</h2>
    }
</div>